name: "🔨 Change request"
description: Don't like something? Request a change!
title: "[Please Change]: "
labels: ["enhancement", "triage"]
assignees:
  - frozensnowy

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to make a change request for Maelfrost!
      Requesting for something to change doesn't mean it actually changes as sometimes it doesn't fit within the project's purpose/design.
      Please make sure to [search for existing change requests](https://github.com/frozensnowy/Maelfrost-bugs-suggestions/issues) before filing a new one!
      ***Please create these change requests in English only***, (use google translate if required)
      
- type: textarea
  attributes: 
    label: What would you like to see change in Maelfrost?
    description: Please be as detailed as possible.
    placeholder: |
      I'd like to change...
  validations:
    required: true
    
- type: textarea
  attributes: 
    label: Why should this change?
    description: Be as detailed as possible.
    placeholder: |
      This has to change because...
  validations:
    required: false
    
- type: textarea
  attributes: 
    label: Additional context
    description: Add any other context, screenshots or mockups for the change request go here. If it's a typo or broken link, tell me where it happens.
  validations:
    required: false    
    
- type: dropdown
  attributes:
    label: Importance
    description: Please indicate how important your problem is.
    multiple: true
    options:
      - High
      - Medium
      - Low
  validations:
    required: true

- type: dropdown
  attributes:
    label: OS Area(s) you'd like the change to happen in?
    description: Where should the change occur?  Check all that apply.
    multiple: true
    options:
      - Everywhere (A major change)
      - A program that ships with Maelfrost
      - The installation process
      - In the customization of Maelfrost
      - In a file or in the registry
      - A default setting
      - Something visual but general (a button or an icon)
      - Somewhere else
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      **Please limit one request per issue.**
