name: "⭐ Feature request"
description: Shape the future of the project
title: "[Request]: "
labels: ["enhancement", "triage"]
assignees:
  - frozensnowy

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to make a feature request for Maelfrost!
      The more complex your request is, the harder it will be to integrate. Making a request doesn't mean it will get implemented.
      Please make sure to [search for existing requests](https://github.com/frozensnowy/Maelfrost-bugs-suggestions/issues) before filing a new one!
      ***Please create these requests in English only***, (use google translate if required)
      
- type: textarea
  attributes: 
    label: What new feature would you like to have added to Maelfrost?
    placeholder: |
      Please add a...
  validations:
    required: true
    
- type: textarea
  attributes: 
    label: Can this issue be solved with a third-party program?
    description: If yes, Which program? Do you want this program integrated into Maelfrost and why (not)? If not, why would writing something from scratch be worth it?

    placeholder: |
      Example: Yes, There are other browsers out there, but they are bloated. Integrating a lightweight, easy to run browser would be more useful.
  validations:
    required: false
    
- type: textarea
  attributes: 
    label: Add any other context, screenshots or mockups for the feature request go here. If you are requesting for third-party software to be integrated into Maelfrost, please link the homepage for it here.
  validations:
    required: false    
    
- type: dropdown
  attributes:
    label: Importance
    description: Please indicate how important your problem is.
    multiple: true
    options:
      - High
      - Medium
      - Low
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      **Please limit one request per issue.**
